// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAI.ATSScore.API.Data;

#nullable disable

namespace ResumeAI.ATSScore.API.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260411062158_AddProjectsPersistenceEf")]
    partial class AddProjectsPersistenceEf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ats_result_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomRole")
                        .HasColumnType("text")
                        .HasColumnName("custom_role");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_role");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ats_results", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ParsedJdJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_jd_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("job_description_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ParsedResumeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_resume_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("resume_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("wizard_state", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithMany("AtsResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("JobDescriptionArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("ResumeArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("WizardState")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Navigation("AtsResults");

                    b.Navigation("JobDescriptionArtifact");

                    b.Navigation("ResumeArtifact");

                    b.Navigation("WizardState");
                });
#pragma warning restore 612, 618
        }
    }
}
