// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAI.ATSScore.API.Data;

#nullable disable

namespace ResumeAI.ATSScore.API.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260413113703_AddTemplateRenderingMetadataAndAssets")]
    partial class AddTemplateRenderingMetadataAndAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ats_result_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomRole")
                        .HasColumnType("text")
                        .HasColumnName("custom_role");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_role");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ats_results", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ParsedJdJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_jd_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("job_description_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ParsedResumeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_resume_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("resume_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuilderSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("builder_snapshot_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("GeneratedResumeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("generated_resume_json");

                    b.Property<string>("GenerationModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generation_model");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finalized");

                    b.Property<string>("LastChangeRequest")
                        .HasColumnType("text")
                        .HasColumnName("last_change_request");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("revision_count");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("resume_builder_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<string>("AssetGroupKey")
                        .HasColumnType("text")
                        .HasColumnName("asset_group_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("PreviewThumbnailBase64")
                        .HasColumnType("text")
                        .HasColumnName("preview_thumbnail_base64");

                    b.Property<string>("RenderContractJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("render_contract_json");

                    b.Property<string>("StyleGuideJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_guide_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TemplateId");

                    b.HasIndex("IsDefault");

                    b.ToTable("resume_builder_templates", "projects");

                    b.HasData(
                        new
                        {
                            TemplateId = "deedy-one-page-two-column",
                            AssetGroupKey = "deedy-default",
                            Category = "professional",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Balanced one-page layout with a strong two-column hierarchy for concise, high-signal resumes.",
                            IsActive = true,
                            IsDefault = true,
                            RenderContractJson = "{\"layoutType\":\"two_column\",\"page\":{\"size\":\"A4\",\"margin\":24},\"columns\":{\"leftRatio\":0.34,\"rightRatio\":0.66,\"gap\":16},\"typography\":{\"fontFamily\":\"Arial\",\"nameSize\":20,\"roleSize\":10,\"sectionTitleSize\":11,\"bodySize\":9,\"smallTextSize\":8},\"colors\":{\"primary\":\"#0f766e\",\"secondary\":\"#111827\",\"muted\":\"#4b5563\"},\"sectionOrder\":{\"left\":[\"summary\",\"skills\",\"education\"],\"right\":[\"experience\",\"projects\"]},\"limits\":{\"maxPages\":1,\"truncateOverflow\":true,\"maxBulletsPerJob\":4,\"maxExperienceItems\":3,\"maxProjectItems\":3}}",
                            StyleGuideJson = "{\"layout\":\"two_column\",\"pageLength\":\"one_page\",\"tone\":\"professional\",\"accentColor\":\"#0f766e\",\"sectionOrder\":[\"summary\",\"skills\",\"experience\",\"projects\",\"education\"]}",
                            Title = "Deedy - One Page Two Column Resume",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TemplateId = "jakes-template",
                            AssetGroupKey = "jakes-default",
                            Category = "professional",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Single-column modern professional template with high readability and strong section rhythm.",
                            IsActive = true,
                            IsDefault = false,
                            RenderContractJson = "{\"layoutType\":\"single_column\",\"page\":{\"size\":\"A4\",\"margin\":28},\"typography\":{\"fontFamily\":\"Arial\",\"nameSize\":22,\"roleSize\":10,\"sectionTitleSize\":12,\"bodySize\":9,\"smallTextSize\":8},\"colors\":{\"primary\":\"#0f172a\",\"secondary\":\"#1f2937\",\"muted\":\"#6b7280\"},\"sectionOrder\":{\"main\":[\"summary\",\"experience\",\"projects\",\"education\",\"skills\"]},\"limits\":{\"maxPages\":1,\"truncateOverflow\":true,\"maxBulletsPerJob\":4,\"maxExperienceItems\":4,\"maxProjectItems\":3}}",
                            StyleGuideJson = "{\"layout\":\"single_column\",\"pageLength\":\"one_page\",\"tone\":\"professional\",\"accentColor\":\"#0f172a\"}",
                            Title = "Jake's Resume Template",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TemplateId = "simple-hipster",
                            AssetGroupKey = "simple-hipster-icons",
                            Category = "creative",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean casual layout with icon-assisted contact header and lightweight visual accents.",
                            IsActive = true,
                            IsDefault = false,
                            RenderContractJson = "{\"layoutType\":\"hipster\",\"page\":{\"size\":\"A4\",\"margin\":26},\"typography\":{\"fontFamily\":\"Arial\",\"nameSize\":21,\"roleSize\":10,\"sectionTitleSize\":11,\"bodySize\":9,\"smallTextSize\":8},\"colors\":{\"primary\":\"#155e75\",\"secondary\":\"#0f172a\",\"muted\":\"#475569\"},\"sectionOrder\":{\"main\":[\"summary\",\"experience\",\"projects\",\"education\",\"skills\"]},\"assets\":{\"iconKeys\":[\"phone\",\"email\",\"linkedin\",\"github\"]},\"limits\":{\"maxPages\":1,\"truncateOverflow\":true,\"maxBulletsPerJob\":3,\"maxExperienceItems\":3,\"maxProjectItems\":3}}",
                            StyleGuideJson = "{\"layout\":\"creative_clean\",\"pageLength\":\"one_page\",\"tone\":\"modern\",\"accentColor\":\"#155e75\"}",
                            Title = "Simple Hipster",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumePdfExportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("PdfBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_bytes");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RenderOptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("render_options_json");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ProjectId");

                    b.ToTable("resume_pdf_exports", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeTemplateAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_key");

                    b.Property<string>("Base64Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base64_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "AssetKey")
                        .IsUnique();

                    b.ToTable("resume_template_assets", "projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f702a82e-6a2b-4ddf-a0ad-f7f0535db001"),
                            AssetKey = "phone",
                            Base64Data = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PGNpcmNsZSBjeD0iOCIgY3k9IjgiIHI9IjciIGZpbGw9IiMwZjc2NmUiLz48cGF0aCBkPSJNNSA0aDJsMSAyLTEgMWMuNSAxIDEuNSAyIDIuNSAyLjVsMS0xIDIgMXYyYy0zLjUuNS03LTMtNy41LTcuNXoiIGZpbGw9IiNmZmYiLz48L3N2Zz4=",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 16,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            TemplateId = "simple-hipster",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Width = 16
                        },
                        new
                        {
                            Id = new Guid("f702a82e-6a2b-4ddf-a0ad-f7f0535db002"),
                            AssetKey = "email",
                            Base64Data = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PHJlY3QgeD0iMSIgeT0iMyIgd2lkdGg9IjE0IiBoZWlnaHQ9IjEwIiByeD0iMiIgZmlsbD0iIzBmNzY2ZSIvPjxwYXRoIGQ9Ik0yIDVsNiA0IDYtNCIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEuMiIgZmlsbD0ibm9uZSIvPjwvc3ZnPg==",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 16,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            TemplateId = "simple-hipster",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Width = 16
                        },
                        new
                        {
                            Id = new Guid("f702a82e-6a2b-4ddf-a0ad-f7f0535db003"),
                            AssetKey = "linkedin",
                            Base64Data = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PHJlY3QgeD0iMSIgeT0iMSIgd2lkdGg9IjE0IiBoZWlnaHQ9IjE0IiByeD0iMiIgZmlsbD0iIzBmNzY2ZSIvPjxjaXJjbGUgY3g9IjUiIGN5PSI1IiByPSIxIiBmaWxsPSIjZmZmIi8+PHJlY3QgeD0iNC4yIiB5PSI2LjUiIHdpZHRoPSIxLjYiIGhlaWdodD0iNSIgZmlsbD0iI2ZmZiIvPjxwYXRoIGQ9Ik04IDYuNWgxLjV2LjhjLjMtLjUuOS0uOSAxLjctLjkgMS4zIDAgMiAuOCAyIDIuNHYyLjdoLTEuNlY5LjFjMC0uOC0uMy0xLjItMS0xLjItLjcgMC0xLjEuNS0xLjEgMS4zdjIuM0g4eiIgZmlsbD0iI2ZmZiIvPjwvc3ZnPg==",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 16,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            TemplateId = "simple-hipster",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Width = 16
                        },
                        new
                        {
                            Id = new Guid("f702a82e-6a2b-4ddf-a0ad-f7f0535db004"),
                            AssetKey = "github",
                            Base64Data = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PGNpcmNsZSBjeD0iOCIgY3k9IjgiIHI9IjciIGZpbGw9IiMxMTE4MjciLz48cGF0aCBkPSJNOCAzLjVhNC41IDQuNSAwIDAgMC0xLjQgOC44di0xLjdjLTEuNi4zLTItLjctMi0uNy0uMy0uNy0uOC0uOS0uOC0uOS0uNy0uNSAwLS41IDAtLjUuOC4xIDEuMi44IDEuMi44LjcgMS4xIDEuOC44IDIuMi42LjEtLjUuMy0uOC41LTEtMS4zLS4xLTIuNy0uNy0yLjctMyAwLS43LjItMS4zLjctMS43LS4xLS4yLS4zLS45LjEtMS45IDAgMCAuNi0uMiAxLjkuN2E2LjUgNi41IDAgMCAxIDMuNCAwYzEuMy0uOSAxLjktLjcgMS45LS43LjQgMSAuMiAxLjcuMSAxLjkuNC41LjcgMSAuNyAxLjcgMCAyLjMtMS40IDIuOS0yLjcgMyAuMy4yLjUuNy41IDEuM3YxLjlBNC41IDQuNSAwIDAgMCA4IDMuNXoiIGZpbGw9IiNmZmYiLz48L3N2Zz4=",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 16,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            TemplateId = "simple-hipster",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Width = 16
                        });
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("wizard_state", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithMany("AtsResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("JobDescriptionArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("ResumeArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("ResumeBuilderArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", "Template")
                        .WithMany("Artifacts")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumePdfExportEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", "Artifact")
                        .WithMany("PdfExports")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeTemplateAssetEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", "Template")
                        .WithMany("Assets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("WizardState")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Navigation("AtsResults");

                    b.Navigation("JobDescriptionArtifact");

                    b.Navigation("ResumeArtifact");

                    b.Navigation("ResumeBuilderArtifact");

                    b.Navigation("WizardState");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.Navigation("PdfExports");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
