// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAI.ATSScore.API.Data;

#nullable disable

namespace ResumeAI.ATSScore.API.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260413062425_AddResumeBuilderWorkflow")]
    partial class AddResumeBuilderWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ats_result_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomRole")
                        .HasColumnType("text")
                        .HasColumnName("custom_role");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_role");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ats_results", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ParsedJdJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_jd_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("job_description_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ParsedResumeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_resume_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("resume_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuilderSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("builder_snapshot_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("GeneratedResumeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("generated_resume_json");

                    b.Property<string>("GenerationModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generation_model");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finalized");

                    b.Property<string>("LastChangeRequest")
                        .HasColumnType("text")
                        .HasColumnName("last_change_request");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("revision_count");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("resume_builder_artifacts", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("StyleGuideJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_guide_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TemplateId");

                    b.HasIndex("IsDefault");

                    b.ToTable("resume_builder_templates", "projects");

                    b.HasData(
                        new
                        {
                            TemplateId = "deedy-one-page-two-column",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Balanced one-page layout with a clean two-column structure for concise, high-signal resumes.",
                            IsActive = true,
                            IsDefault = true,
                            StyleGuideJson = "{\"layout\":\"two_column\",\"pageLength\":\"one_page\",\"tone\":\"professional\",\"accentColor\":\"#0f766e\",\"sectionOrder\":[\"summary\",\"skills\",\"experience\",\"projects\",\"education\"]}",
                            Title = "Deedy - One Page Two Column Resume",
                            UpdatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumePdfExportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("PdfBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_bytes");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RenderOptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("render_options_json");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ProjectId");

                    b.ToTable("resume_pdf_exports", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("wizard_state", "projects");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.AtsResultEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithMany("AtsResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("JobDescriptionArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.JobDescriptionArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("ResumeArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.ResumeArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("ResumeBuilderArtifact")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", "Template")
                        .WithMany("Artifacts")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumePdfExportEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", "Artifact")
                        .WithMany("PdfExports")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", b =>
                {
                    b.HasOne("ResumeAI.ATSScore.API.Persistence.ProjectEntity", "Project")
                        .WithOne("WizardState")
                        .HasForeignKey("ResumeAI.ATSScore.API.Persistence.WizardStateEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ProjectEntity", b =>
                {
                    b.Navigation("AtsResults");

                    b.Navigation("JobDescriptionArtifact");

                    b.Navigation("ResumeArtifact");

                    b.Navigation("ResumeBuilderArtifact");

                    b.Navigation("WizardState");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderArtifactEntity", b =>
                {
                    b.Navigation("PdfExports");
                });

            modelBuilder.Entity("ResumeAI.ATSScore.API.Persistence.ResumeBuilderTemplateEntity", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
